project:
  type: website
  output-dir: _site

website:
  title: "Embargo Breach: Tracing TenantThread's AI Crisis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: proposal.qmd
        text: Proposal
      - text: Methodology
        menu:
          - href: methodology/data-preparation.qmd
            text: Data Preparation
            
          - href: methodology/feature-engineering.qmd
            text: Feature Engineering
            
          - href: methodology/visual-analytics-design.qmd
            text: Visual Analytics Design
            
      - href: findings.qmd
        text: Findings
        
      - href: poster.qmd
        text: Poster
        
      - text: Meeting Minutes
        menu:
          - href: meeting-minutes/mom1.qmd
            text: Minute of Meeting 1

    right:
      - href: about.qmd
        text: The Team
        
      - text: Shiny App
        menu:
          - href: user-guide.qmd
            text: User Guide
            
          - href: https://visual-analytics-project-apr26.shinyapps.io/tenantthread-embargo-breach/
            text: Launch Shiny App
        
      - text: GitHub
        menu:
          - href: https://github.com/belletandra/vaa_project
            text: Project Website Repository
            
          - href: https://github.com/kellieklarks0n/shinyvaa
            text: Shiny App Repository
        
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

