project:
  type: website
  output-dir: _site

website:
  title: "Embargo Breach: Tracing TenantThread's AI Crisis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: proposal.qmd
        text: Proposal
      - text: Methodology
        menu:
          - href: methodology/data-preparation.qmd
            text: Data Preparation
            
          - href: methodology/feature-engineering.qmd
            text: Feature Engineering
            
          - href: methodology/visual-analytics-design.qmd
            text: Visual Analytics Design
            
      - href: findings.qmd
        text: Findings
        
      - href: poster.qmd
        text: Poster
        
      - text: Meeting Minutes
        menu:
          - href: meeting-minutes/mom1.qmd
            text: Minute of Meeting 1

    right:
      - href: about.qmd
        text: The Team
        
      - text: Shiny App
        menu:
          - href: user-guide.qmd
            text: User Guide
            
          - href: shiny.qmd
            text: Launch Shiny App
        
      - text: GitHub
        menu:
          - href: github.qmd#project-website-repository
            text: Project Website Repository
            
          - href: github.qmd#shiny-app-repository
            text: Shiny App Repository
        
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

